# Generated by Django 5.2.8 on 2025-12-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('canceled', 'Cancelado')], default='scheduled', max_length=20),
        ),
    ]
