# Generated by Django 5.2.8 on 2025-12-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
